import React from 'react'

export const metadata = {
  title: "Política y Privacidad | EASYLAV",
  description: "Generated by create next app",
};

const PoliticaPrivacidad = () => {
  return (
    <div>Política y Privacidad</div>
  )
}

export default PoliticaPrivacidad