import React from 'react'

export const metadata = {
  title: "Contacto | EASYLAV",
  description: "Generated by create next app",
};

const Contacto = () => {
  return (
    <div>Contacto</div>
  )
}

export default Contacto