import React from 'react'

export const metadata = {
  title: "Terminos y Condiciones | EASYLAV",
  description: "Generated by create next app",
};

const TerminosCondiciones = () => {
  return (
    <div>Terminos y Condiciones</div>
  )
}

export default TerminosCondiciones