import React from 'react'

export const metadata = {
  title: "Franquicias | EASYLAV",
  description: "Generated by create next app",
};

const Franquicias = () => {
  return (
    <div>Franquicias</div>
  )
}

export default Franquicias