import React from 'react'

export const metadata = {
  title: "Sucursales | EASYLAV",
  description: "Generated by create next app",
};

const Sucursales = () => {
  return (
    <div>Sucursales</div>
  )
}

export default Sucursales